*Engi 9981/ ME 7220 Guidance Navigation and Control for Autonomy*


# **1.1 Mathematical Preliminaries**

<a href="https://colab.research.google.com/drive/1pshiUZHJ_zSQCLciRR91sGGCvTTuxMQP?usp=sharing" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

This topics reviews the mathematical background and introduces the notations used throughout this course. This is a Colab notebook which can be open in a browser using the following link: https://colab.research.google.com/drive/1pshiUZHJ_zSQCLciRR91sGGCvTTuxMQP?usp=sharing. And copied to include your code and note additions.


The topics covered include vectors, frames, rotations, groups. And how they can be used to come up with a `mathematical model` for a given system. In robotic applications, development of these models involves rigid body modelling kinematics and dynamics .



## **2D and 3D vectors**
* Scalars, vectors, and matrices are predominantly used in the formulation of mathematical models of dynamical systems.  
* A vector $\mathbf{p}\in \mathbb{R}^3$ is a mathematical object that can be used to represent a magnitude given by $||\mathbf{p}||$ and a 3 dimensional direction given by $\vec{\mathbf{p}}=\mathbf{p}/||\mathbf{p}||$. Here the operator $||\cdot||$ is the norm of a vector and unit vectors are denoted using $\vec{\cdot}$ notation.
* A vector can be two dimentional (2D) to help with planar modeling tasks and there dimentinoal (3D) for spatial modeling tasks. We will also use higher dimensional vectors when representing rotations and combination of such quantities. 
* 3D vectors can be used to represent different physical quantities. e.g., position $\mathbf{p}$, velocity $\mathbf{v}$, angular velocity $\boldsymbol{\omega}$.
*  For example the angular rotation of the earth can be written as $\boldsymbol{\omega} = \begin{bmatrix} 0& 0& 7.2921159\times 10^{-5} \end{bmatrix}^T rad/s$ if z axis is defined such that it is along the rotation axis of the earth. Note that we have denoted this as a column vector which is common pracitce when denoting vectors.


### **Vector notation and operations**
* When it comes to position, we can denote the position of point $b$ relative to point $a$ using subscripts of a position vector $\mathbf{p}_{ab}$. Similarly, we can denote the velocity of point $b$ relative to point $a$ using subscripts of a velocity vector $\mathbf{v}_{ab}$.


* Scalar multiplication of a vector, scales the magnitude of the vector, where 
\begin{equation}
\begin{array}{c}
||s\mathbf{p}||=s||\mathbf{p}|| \\
\vec{s\mathbf{p}}=\vec{\mathbf{p}}
\end{array}
\end{equation}.

* For example changing the units of $\boldsymbol{\omega}$ defined earlier can be achieved by scalar multiplication as follows:
\begin{equation}
\boldsymbol{\omega}= \frac{60}{2\pi}\begin{bmatrix} 0& 0& 7.2921159\times 10^{-5} \end{bmatrix}^T  rpm
\end{equation}.

* Addition of vectors always follow the linking of subscripts, where:
\begin{equation}
\mathbf{p}_{ac}=\mathbf{p}_{ab}+\mathbf{p}_{bc}
\end{equation}.


<center>
<div>
<img src="https://drive.google.com/uc?export=view&id=1uc0pY_F-ZlwrhJaMMhnH_zVQuHU8Iql5"
    width="700"/>
</div>
</center>

* The negative of a vector can be defined as follows:
\begin{equation}
^w\mathbf{p}_{wb}=-^w\mathbf{p}_{bw}
\end{equation}.



<center>
<div>
<img src="https://drive.google.com/uc?export=view&id=1wKs5VrLMCKrImQ6o8NOhhr-D4RMRB8qT"
    width="700"/>
</div>
</center>


* The projected length of vector $\mathbf{a}$ along the direction of vector $\mathbf{b}$ is given by the dot product $\mathbf{a}^T\vec{\mathbf{b}}$. The dot product is defined as follows where $\theta$ is the angle between the two vectors.
<center>
<div>
<img src="https://drive.google.com/uc?export=view&id=1u0_ynr00OnTNl-iJTy937bDhLxPoTyiv"
    width="250"/>
</div>
</center>



\begin{equation}
\mathbf{a}\cdot\mathbf{b}=\mathbf{a}^T\mathbf{b}=||\mathbf{a}|||\mathbf{b}||cos\theta
\end{equation}.

* The cross product between the same two vectors produces a vector perpendicular to $\mathbf{a}$ and $\mathbf{b}$ having a length of $||\mathbf{a}||||\mathbf{b}||sin\theta$. The cross product is defined as follows where $\vec{\mathbf{n}}$ is the normal vector direction $\vec{\mathbf{a}}\times \vec{\mathbf{b}}$.

\begin{equation}
\mathbf{a}\times \mathbf{b}=||\mathbf{a}|||\mathbf{b}||sin\theta~ \vec{\mathbf{n}}
\end{equation},

<center>
<div>
<img src="https://drive.google.com/uc?export=view&id=1pqke-3ACLLcK-FofSbaJHd3ThIzQYVg_"
    width="250"/>
</div>
</center>



# **Frames of Reference - Rotation Matrices**

* Three perpendicular unit vectors $\vec{\mathbf{x}},\vec{\mathbf{y}},\vec{\mathbf{z}}$ arranged in a right handed coordinate system, i.e.,  $\vec{\mathbf{x}}\times\vec{\mathbf{y}}=\vec{\mathbf{z}}$ defines a coordinate frame.
* A coordinate frame labeled W is defined using notation $\{W\}$.
* The pose between two reference frames $\{W\}$ and $\{B\}$ can be represented using a position vector $^w\mathbf{p}_{wb}\in R^3$ and a rotation matrix $^w\mathbf{R}_b$.

* The vector $^w\mathbf{p}_{wb}$ should be read as the location of $\{B\}$ relative to $\{W\}$ expressed in frame $\{W\}$. The vector represents the location of the origin of $\{B\}$  relative to origin of $\{W\}$ when measured along the principal axis of $\{W\}$ .

* The rotation matrix  $^w\mathbf{R}_b$ should be read as the orientation of frame $\{B\}$ expressed in $\{W\}$. Rotation matrices have several unique properties. 






## **Properties of Rotation matrices** 


1. The rotation matrix $^w\mathbf{R}_b$ allows to rotate vectors from frame $\{B\}$  to frame $\{W\}$. i.e. given a vector $\textbf{p}_{wb}^b$  expressed in frame $\{B\}$, we can find the vector $\mathbf{p}_{wb}^w$ as follows:

\begin{equation}
^w\mathbf{p}_{wb}= ~^w\mathbf{R}_b ~^b\mathbf{p}_{wb}
\end{equation}

2. For three dimensional rotations, rotation matrices have a dimension of $3 \times 3$.

3. Matrix inverse of a rotation matrix ${\mathbf{R}_o^w}^{-1}$ is equal to $\mathbf{R}_w^o$ (orthonormal) ,i.e., denotes the rotation of a follower frame $\{W\}$ w.r.t. a base frame $\{O\}$.
\begin{equation}
{\mathbf{R}_o^w}^T={\mathbf{R}_o^w}^{-1}
\end{equation}


4. Rotation matrices are orthogonal and have a determitant of 1. Rotation matrices belong to the special orthogonal group of 3 dimensions SO(3), i.e., $R\in SO(3)$ which defines 3x3 orthonormal matrices representing 3D rotations.
> We will discuss more about groups later in the course, but for now a mathematical group only has one type of operation defined on it ( in the SO3 case matrix multiplication serves as the group operation). Addition operation is inconsistent with the SO3 group because addition of two rotation matrices does not result in a rotation matrix (3x3 orthonorma matrix). In contrast 3D vectors which belong to the euclidean vector space ($\mathbb{R}^3$) results in a vector of the same vector space ($\mathbb{R}^3$) regardless of the fundamental operations: scalar multiplicaiton and addition. 

5. Right-hand rule can be used to find the positive direction of rotation. i.e., CCW rotation about an axis is positive.

6. Rotations about the principal axis' follows a predictable pattern.

\begin{equation}
\begin{array}{c c}
Rot(x, \psi)=\begin{bmatrix} 1 & 0 &0\\ 0  &  \cos \psi  &-\sin \psi\\ 0 &\sin \psi  &\cos \psi \end{bmatrix}&
Rot(y, \theta)=\begin{bmatrix} \cos \theta &0 & \sin \theta \\ 0 &1 &0\\-\sin \theta &0 &  \cos \theta \end{bmatrix}\\
Rot(z, \phi)=\begin{bmatrix} \cos \phi &- \sin \phi &0\\ \sin \phi  &  \cos \phi &0\\ 0 &0 &1 \end{bmatrix} \\              
\end{array}
\end{equation}



7. Rotations can be combined by matrix multiplication and the rotation sequence depends on the order in which they are applied.


<center>
<div>
<img src="https://drive.google.com/uc?export=view&id=1fDKdsSgUtI7t5uHg8qHflrpNIFNItRqQ"
    width="600"/>
</div>
</center>


# **Using python numpy for vector matrix math**

Now we will look at how to use vectors and matrices in python scripts. The following code performs basic vector addition using python. The `np.array()` command is used to define vectors and `print()` command is used to display the elements of a vector.

In [1]:
import numpy as np   #numpy package is used to handle vectors, matrices and associated linear algebra operations

p_wa_w=  np.array([1,0,0])
p_ab_w=  np.array([1,1,0])
p_wb_w= p_wa_w + p_ab_w

#print(p_wa_w)
#print(p_ab_w)
print('p_wb_w=',p_wb_w)

# A matrix can be defined using the following syntax
R_b_w =  np.array([[0,0,1],[0,1,0],[1,0,0]])

print('R_w_b=', R_b_w)

p_wb_b = R_b_w @ p_wb_w # @ symbol is used for matrix multiplaction
print('p_wb_b=',p_wb_b)

print(R_b_w)

p_wb_w= [2 1 0]
R_w_b= [[0 0 1]
 [0 1 0]
 [1 0 0]]
p_wb_b= [0 1 2]
[[0 0 1]
 [0 1 0]
 [1 0 0]]


Note that the syntax follow a certain set of rules. The quickest way for Matlab users to make the transition is to use the following guide:
https://numpy.org/doc/stable/user/numpy-for-matlab-users.html

You can try operations like accessing rows and columns of a matrix, finding transpose, inverse, matrix multiplication by using the matlab to numpy cheat sheet above.

In [ ]:
# TRY YOUR FAVOURITE MATLAB VECTOR MATRIX OPERATIONS HERE BY FOLLOWING THE ABOVE CHEAT SHEET

### **Example 1.1**


>Write a function $\mathbf{rotnp(`axis',angle)}$ to return the rotation matrix corresponding to a rotation about an principal axis ('x','y', or 'z') and a numerical angle specified by the user. Use the function to find the rotation matrix corresponding to a rotation of $\pi/3$ about the z axis.




In [2]:
#First lets use numpy for vector matrix math
import numpy as np

def rotnp(a,b):   
      c=np.cos(b)
      s=np.sin(b)
      if a=="z":
        R = np.array([[c,-s,0],
        [s,c,0],
        [0,0,1]])
      if a=="x":
        R = np.array([[1,0,0],
        [0,c,-s],
        [0,s,c]])
      if a=="y":
        R = np.array([[c,0,s],
        [0,1,0],
        [-s,0,c]])
      return(R)

#test the function
R = rotnp('z',np.pi/3)
print(R)
R = rotnp('x',np.pi/10)
print(R)

[[ 0.5       -0.8660254  0.       ]
 [ 0.8660254  0.5        0.       ]
 [ 0.         0.         1.       ]]
[[ 1.          0.          0.        ]
 [ 0.          0.95105652 -0.30901699]
 [ 0.          0.30901699  0.95105652]]


### **Exercise 1.1**

>Write a function $\mathbf{skew(v)}$ to return the skew symetric matrix corresponding to a given numpy vector $\mathbf{v}$. Use the function to find the the cross product of  vector $\mathbf{a}= \begin{bmatrix} 1 &5 &6 \end{bmatrix}^T $ and $\mathbf{b}= \begin{bmatrix} 2 &9 &1 \end{bmatrix}^T $, i.e., $\mathbf{a} \times \mathbf{b}$.

In [3]:
# WRITE YOUR CODE HERE

import numpy as np

def skew(V):

  a = np.array([1,5,6])
  b = np.array([2,9,1])

  V = np.cross(a,b)

  return V



### **Exercise 1.2**

>Write a function $\mathbf{dot(a,b)}$ to return the dot product between  vector $\mathbf{a}= \begin{bmatrix} 1 &5 &6 \end{bmatrix}^T $ and $\mathbf{b}= \begin{bmatrix} 2 &9 &1 \end{bmatrix}^T $, i.e., $\mathbf{a} . \mathbf{b}$.

In [4]:
# WRITE YOUR CODE HERE
import numpy as np
a = np.array([1,5,6]).T
b = np.array([1,5,6]).T

A = np.array([[1,5,6],[1,5,6],[1,5,6]])



# **Using python sympy for symbolic math**
You can do same using symbols as below using the sympy package. Using a symbolc version of the matrix, operations like differentiation can be easily performed using the sympy library.

### **Example 1.2**
>Write a function $\mathbf{rotsym(`axis',angle)}$ to return the rotation matrix corresponding to a rotation about an principal axis ('x','y', or 'z') and a symbolic angle specified by the user. Use the function to find the rotation matrix corresponding to a rotation of $\pi/3$ about the z axis. 

In [6]:
import sympy  
import numpy as np

def rotsym(a,b):
    c=sympy.cos(b)
    s=sympy.sin(b)
    if a=="z":
        R = sympy.Matrix([[c,-s,0],
        [s,c,0],
        [0,0,1]])
    if a=="x":
        R = sympy.Matrix([[1,0,0],
        [0,c,-s],
        [0,s,c]])
    if a=="y":
        R = sympy.Matrix([[c,0,s],
        [0,1,0],
        [-s,0,c]])
    return(R)

#test the function
R = rotsym('z',sympy.pi/3)
R

Matrix([
[      1/2, -sqrt(3)/2, 0],
[sqrt(3)/2,        1/2, 0],
[        0,          0, 1]])

> Find the differentiation of a rotation matrix with respect to $\theta$. i.e.,  $\frac{d}{d \theta}R_z(\theta)$?

In [7]:
θ =sympy.Symbol('θ')
R = rotsym('z',θ)
sympy.diff(R,θ)

Matrix([
[-sin(θ), -cos(θ), 0],
[ cos(θ), -sin(θ), 0],
[      0,       0, 0]])

### **Exercise 1.3**

>Write a function $\mathbf{skewsym(v)}$ to return the skew symetric matrix corresponding to a given sympy vector $\mathbf{v}$. 

>(a) Use the function to find the the cross product of  vector $\mathbf{a}= \begin{bmatrix} a_x &a_y &a_z \end{bmatrix}^T $ and $\mathbf{b}= \begin{bmatrix} b_x &b_y &b_z \end{bmatrix}^T $, i.e., $\mathbf{a} \times \mathbf{b}$.

>(b) Find the the following differentiation $\displaystyle \frac{\partial (\mathbf{a} \times \mathbf{b})}{\partial a_z}$.

# **Rotation representaiton - Euler angles**

A minimal representation of 3D rotations is achieved using Euler angles. The method uses 3 angles roll, pitch, and yaw to rotate with respect to a reference frame $\{W\}$. It is common practice to follow the ZYX rotation sequence, i.e., starting at a base frame $\{W\}$  ending on a follower frame $\{O\}$. Rotate $\psi$ about z axis of frame $\{W\}$ to reach frame $\{O_1\}$, then rotate $\theta$ about y axis of frame $\{O_1\}$ to reach frame $\{O_2\}$, then rotate $\phi$ about x axis of frame $\{O_2\}$ to reach frame $\{O\}$.

https://compsci290-s2016.github.io/CoursePage/Materials/EulerAnglesViz/

### **Example 1.3**
>Roll $(\phi)$, pitch$(\theta)$, yaw$(\psi)$ axis convention  is commonly used to parameterize 3D rotations using 3 angles (also known as ZYX Euler angles). This corresponds to the following sequence of rotations starting at a base frame $\{W\}$  ending on a follower frame $\{O\}$. Rotate $\psi$ about z axis of frame $\{W\}$ to reach frame $\{O_1\}$, then rotate $\theta$ about y axis of frame $\{O_1\}$ to reach frame $\{O_2\}$, then rotate $\phi$ about x axis of frame $\{O_2\}$ to reach frame $\{O\}$. Find rotation matrix $~^wR_o$? What is the rotation matrix if roll, pitch, and yaw are $\pi/3, -\pi/4 , \pi/10$ respectively.


<center>
<div>
<img src="https://drive.google.com/uc?export=view&id=16ZJ-i-4Uos4LLdOx6Miri1o9mSwPAwMM"
    width="300"/>
</div>
</center>

The following code evaluates the answer using the *rotsym* function.


In [8]:
θ = sympy.Symbol('θ')
ϕ = sympy.Symbol('ϕ')
ψ = sympy.Symbol('ψ')
R=rotsym("z",ψ)*rotsym("y",θ)*rotsym("x",ϕ)
R


Matrix([
[cos(θ)*cos(ψ), sin(θ)*sin(ϕ)*cos(ψ) - sin(ψ)*cos(ϕ), sin(θ)*cos(ψ)*cos(ϕ) + sin(ψ)*sin(ϕ)],
[sin(ψ)*cos(θ), sin(θ)*sin(ψ)*sin(ϕ) + cos(ψ)*cos(ϕ), sin(θ)*sin(ψ)*cos(ϕ) - sin(ϕ)*cos(ψ)],
[      -sin(θ),                        sin(ϕ)*cos(θ),                        cos(θ)*cos(ϕ)]])

In [9]:
#Substituting values and simplifying symbolic expressions can be done using sympy.Sus and simpy.simplify methods
# sympy.pi produces better numerical precision
newR = R.subs({ψ:sympy.pi/10, θ:-sympy.pi/4, ϕ:sympy.pi/3,})
newR = sympy.simplify(newR)
newR

#newR.evalf(). # this converts the above to floating point numbers


Matrix([
[    sqrt(sqrt(5) + 5)/4,          -sqrt(3*sqrt(5) + 15)/8 - sqrt(5)/8 + 1/8,      -sqrt(sqrt(5) + 5)/8 - sqrt(3)/8 + sqrt(15)/8],
[-sqrt(2)/8 + sqrt(10)/8, -sqrt(30)/16 + sqrt(6)/16 + sqrt(2*sqrt(5) + 10)/8, -sqrt(6*sqrt(5) + 30)/8 - sqrt(10)/16 + sqrt(2)/16],
[              sqrt(2)/2,                                          sqrt(6)/4,                                          sqrt(2)/4]])

### **Exercise 1.4**

> If the pitch angle of an aircraft with body fixed frame $\{O\}$ is $-\pi/2$, find the resulting rotation matrix $~^wR_o$ for a roll angle of $\phi$ and a yaw angle of $\psi$. Assume ZYX Euler angles.  At this configuration, comment on how many effective degrees of freedom are remaining for rotations in 3D?

In [10]:
#R=rotsym("x",ϕ)*rotsym("y",θ)*rotsym("z",ψ)
B= sympy.Subs(R,θ,-sympy.pi/2)
C = sympy.simplify(sympy.simplify(B))
C 

# both roll and yaw results in rotations about the z axis of the world frame. 
# So rotational degrees of freedom has reduced to one axis

Matrix([
[0, -sin(ψ + ϕ), -cos(ψ + ϕ)],
[0,  cos(ψ + ϕ), -sin(ψ + ϕ)],
[1,           0,           0]])

# **Key Vector Matrix Identities**
The following is a summary of relationships related to vectors and matrix differentiation which are important in the development that follows:

Expressing vector in a different frame
\begin{equation}
\begin{array}{c l}
\mathbf{p}^a_{ab} &= ~^a\mathbf{R}_b\mathbf{p}^b_{ab}\\
\end{array}
\end{equation}

Vector addition
\begin{equation}
\begin{array}{c l}
\mathbf{p}^a_{ac} &=\mathbf{p}^a_{ab}+\mathbf{p}^a_{bc}\\
&=\mathbf{p}^a_{ab}+\mathbf{R}^a_b\mathbf{p}^b_{bc}\\
\end{array}
\end{equation}

Vector substraction
\begin{equation}
\begin{array}{c l}
\mathbf{p}^a_{ab} &= - \mathbf{p}^a_{ba} = -\mathbf{R}^a_b\mathbf{p}^b_{ba}\\
\end{array}
\end{equation}

Skew symmetric representation
\begin{equation}
\boldsymbol{\omega} \times \mathbf{r} = [\boldsymbol{\omega}]_{\times}\mathbf{r} = -[\mathbf{r}]_{\times}\boldsymbol{\omega} 
\end{equation}

Skew symmetric transpose
\begin{equation}
[\boldsymbol{\omega}_{wb}^w]_{\times}^T  = -[\boldsymbol{\omega}_{wb}^w]_{\times} = [\boldsymbol{\omega}_{bw}^w]_{\times}
\end{equation}

Rotation kinematics (this result can be derived following the procedure shown in Appendix A)
\begin{equation}
\dot{\mathbf{R}_b^w} = ~\mathbf{R}_b^w[\boldsymbol{\omega}_{wb}^b]_{\times} 
\end{equation}

Expressing angular velocity skew matrix in a different frame:
\begin{equation}
[\boldsymbol{\omega}_{wb}^w]_{\times} =[\mathbf{R}_b^w~\boldsymbol{\omega}_{wb}^b]_{\times} = \mathbf{R}^w_b[\boldsymbol{\omega}_{wb}^b]_{\times}{\mathbf{R}^w_b}^T 
\end{equation}

Matrix inversion/ transpose lemma
\begin{equation}
(\mathbf{A}\mathbf{B})^T=\mathbf{B}^T\mathbf{A}^T
\end{equation}

Differentiation of a vector matrix product
\begin{equation}
\frac{d}{dt}(\mathbf{A}\mathbf{b})=\dot{\mathbf{A}}\mathbf{b}+\mathbf{A}\dot{\mathbf{b}}
\end{equation}

Differentiationof a vector expressed in a rotating frame of referece
\begin{equation}
\frac{d}{dt}(\mathbf{v}^b)=\frac{d}{dt}(\mathbf{R}^T\mathbf{v}^w)=\dot{\mathbf{R}}^T\mathbf{v}^w+\mathbf{R}^T\dot{\mathbf{v}}^w 
\end{equation}




### **Example 1.4 - 3D Kinematics**
>The following figure identifies three position vectors $\mathbf{p}^a,~\boldsymbol{\rho}^a$ and $\mathbf{r}^b$. 

<center>
<div>
<img src="https://drive.google.com/uc?export=view&id=1Nlyb4AwJ2BPbhsvzIDIm0NtMbSoLF2JW"
    width="400"/>
</div>
</center>


>Show that 
\begin{equation*}
\ddot{\mathbf{p}}^a=\ddot{\boldsymbol{\rho}}^a+\mathbf{R}_b^a(\ddot{\mathbf{r}}^b+2\mathbf{\Omega}_{ab}^b\dot{\mathbf{r}}^b 
+\dot{\mathbf{\Omega}}_{ab}^b\mathbf{r}^b+(\mathbf{\Omega}_{ab}^b)^2\mathbf{r}^b)
\end{equation*}




<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />

<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />

<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />

### **Example 1.5 -  Rotation Dynamics**
>Derive the Euler equation of motion for a rigid body with Inertia $\mathbf{I}^b$ expressed in body fixed frame $\{B\}$.
\begin{equation*}
\boldsymbol{\Gamma}^b_{ib}= \mathbf{I}^b \boldsymbol{\alpha}_{ib}^b+\boldsymbol{\omega}_{ib}^b\times  \mathbf{I}^b\boldsymbol{\omega}_{ib}^b
\end{equation*}


<br />



<center>
<div>
<img src="https://drive.google.com/uc?export=view&id=1VPhC4eBwUgXLwLjvPipzU9ErBYtuNh7e"
    width="700"/>
</div>
</center>


## **Exercise 1.5**
>Figure below illustrates two body fixed frames $\{A\}$ and $\{B\}$ attached to two robots, and an earth fixed navigation frame $\{W\}$. Starting from the vector relationship $\mathbf{p}^w_{wb}=\mathbf{p}^w_{wa}+\mathbf{p}^w_{ab}$, show that 
\begin{equation*}
\dot{\mathbf{p}}^a_{ab}=-\mathbf{v}_{wa}^a+\mathbf{R}_b^a \mathbf{v}_{wb}^b-\boldsymbol{\omega}_{wa}^a\times\mathbf{p}^a_{ab}
\end{equation*}
where $\mathbf{p}$ denotes position vectors, $\mathbf{v}$ denotes velocity vectors, $\boldsymbol{\omega}$ denotes the angular velocity vectors and $\mathbf{R}$ denotes the rotation matrice.

<center>
<div>
<img src="https://drive.google.com/uc?export=view&id=13uC3p9Sq1SafP9rgL-zkSUi6X6lofxkC"
    width="500"/>
</div>
</center>

<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />

## **Exercise 1.6**
> The rotation kinematics in euler angles can be found by expressing the roll pitch and yaw rates in the body fixed frame of reference. Find J1 and J2 of the folllowing equations using hand calculation or sympy. 

> Comment on the solvability of the left hand side of equations (1) and (2) when the pitch angle becomes 90 degrees. 




In [ ]:
θ = sympy.Symbol('θ')
ϕ = sympy.Symbol('ϕ')
ψ = sympy.Symbol('ψ')

e1 = sympy.Matrix([1,0,0])
e2 = sympy.Matrix([0,1,0])
e3 = sympy.Matrix([0,0,1])

J1 = sympy.Matrix.hstack(e1,rotsym("x",ϕ).T @ e2,  rotsym("x",ϕ).T*rotsym("y",θ).T @ e3)
display(J1)
J2 = sympy.simplify(J.inv())
display(J2)

Matrix([
[1,       0,       -sin(θ)],
[0,  cos(ϕ), sin(ϕ)*cos(θ)],
[0, -sin(ϕ), cos(θ)*cos(ϕ)]])

Matrix([
[1, sin(ϕ)*tan(θ), cos(ϕ)*tan(θ)],
[0,        cos(ϕ),       -sin(ϕ)],
[0, sin(ϕ)/cos(θ), cos(ϕ)/cos(θ)]])

# **Rotation representation - Quaternions**

* Thus far we've looked at two ways of representing rotations, i.e., rotation matrices and Euler angles. 
* In Exercise 1.6 we showed that the Euler angle parameterization can approach singularity (gimbal lock) at `pitch=90`, while Rotation matrices maintains the ability to operate without approaching numerical singularities. 
* However the number of paramters of rotation matrices is 9 which makes mathmatical programming heavily overparameterized to overcome the singularity issue. 
* Unit quaternion parameterization uses a  4 dimensional unit vector to represent rotations with the desirable property of not producing singular results at gimbal lock configurations. 
* The rotation kinematics using quaternion parameterization can be represented as below which is singularity free. 
*Quaternions still have an undesirable property termed double wrapping i.e., there are two quaternions that can represent the same unique rotation in SO3. 

* This can be avoided in practice by forcing the first element of the quaternion to be always positive. Thereby forcing a one to one mapping using unit quaternions. 


* There are other parameterizations that are commonly used in practice especially for mathematical analysis. 
* `Axis angle` parameterization represents any arbitary 3D rotation as a rotation about a 3D unit vector $\vec{\mathbf{a}}$ with an angle $\phi$.  
* `Rotationa vector` parameterization represents the axis and the angle as a single vector as follows:
\begin{equation}
\boldsymbol{\theta}=\vec{\mathbf{a}}.\phi
\end{equation}. 
* Note that both these representations (axis angle and rotation vector) wraps around at 180 degrees, hence have a discontinuity at 180. But these are important paramters to know as it will be heavily used when dealing with mathematical optimizations and analysis involving rotations in 3D.

<center>
<div>
<img src="https://drive.google.com/uc?export=view&id=1ga-wjYwaP40eWKRsZfqXD31MybKx7o8G"
    width="550"/>
</div>
</center>


### **Example 1.6**

>The orientation of a body frame is having a roll of $15^{\circ}$, a pitch of $30^{\circ}$, and a yaw of $45^{\circ}$. Express this rotation as 
1.   Rtoation Matrix $R$
2.   Quarternion $\boldsymbol{q}$
3.   Rotation vector $\boldsymbol{\theta}$
4.   Axis angle $(\boldsymbol{a},\phi)$
* For this we use a the jaxlie package.

In [ ]:
%%capture  
#the above line surpresses the output of this cell
!pip install jaxlie

In [1]:
import numpy as np
from jaxlie import SO3
from numpy import pi

#The rotation is expressed as an SO3 type. This allows to do all differnet representations easily
Rot = SO3.from_rpy_radians(30/180*pi,90/180*pi,0/180*pi)  #initialize from RPY
#Rot = SO3(np.array([0.89769256 0.01828305 0.28532013 0.33527035])) #initialize from quaternion
#Rot = SO3.from_matrix(np.array([[ 0.61237246, -0.59150636,  0.524519  ],
#                                [ 0.6123724,   0.7745191 ,  0.15849364],
#                                [-0.49999997,  0.22414386,  0.8365163 ]])) #initialize from mat
#Rot = SO3.exp(np.array([0.03786646, 0.59093344, 0.69438654])) #initialize from rot vector

# Rotation in 4 different forms
print("1.As Rotation Matrix :")
print(Rot.as_matrix())
print("2.As Quarternion :",np.array(Rot.parameters()))
print("3.As Rotation Vector :",Rot.log())
print("4.As Axis angle :",np.linalg.norm(Rot.log()), Rot.log()/np.linalg.norm(Rot.log()))
print("5.As Euler Angles :",np.array([Rot.compute_roll_radians(),Rot.compute_pitch_radians(),Rot.compute_yaw_radians()]))



1.As Rotation Matrix :
[[ 3.7252903e-08  5.0000000e-01  8.6602539e-01]
 [ 0.0000000e+00  8.6602545e-01 -5.0000000e-01]
 [-9.9999994e-01  0.0000000e+00  5.9604645e-08]]
2.As Quarternion : [ 0.68301266  0.1830127   0.68301266 -0.1830127 ]
3.As Rotation Vector : [ 0.41038024  1.5315598  -0.41038024]
4.As Axis angle : 1.6378337 [ 0.25056282  0.93511313 -0.25056282]
5.As Euler Angles : [ 0.04554163  1.5703081  -0.04554163]


### **Exercise 1.7**

>The orientation of a body frame is having the following quarternion $q = [ 0.0 ,-1.0, 0.0 , 0.0]$. Express the rotation as following:
1.   Rotation Matrix $R$
2.   Roll pitch Yaw $(roll~,pith~,yaw)$
3.   Rotation vector $\boldsymbol{\theta}$
4.   Axis angle $(\boldsymbol{a},\phi)$

# **Appendix A - Key Proofs**

Show that $\mathbf{R}_{a(t+\delta t)}^{a(t)}=\mathbf{I}+\boldsymbol{\delta\theta}_{\times}$, where $\boldsymbol{\delta\theta}=(\delta\theta_x,~\delta\theta_y,~\delta\theta_z)^T$ denotes infinitesimal rotations about $x,~y$ and $z$ axis which occurs during $\delta t$.  Using the result show that $\dot{\mathbf{R}}_b^a=\mathbf{R}_b^a\mathbf{\Omega}_{ab}^b$


<center>
<div>
<img src="https://drive.google.com/uc?export=view&id=1rH1XZsQFyi3bRKdSGAs-ovq91BL43clx"
    width="500"/>
</div>
</center>


<center>
<div>
<img src="https://drive.google.com/uc?export=view&id=1aDYitfYOOqItVHBVbK4W58iYx0EMR07c"
    width="500"/>
</div>
</center>
